### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by tobigithub** [icdishb/fingerid#1]
Hi,
probably trivial for python experts, but for UBUNTU that would be

````R
$sudo python setup.py install Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
````

**Ubuntu Solution (maybe add to readme):**
sudo apt-get update
sudo apt-get install python-pip python-setuptools python-numpy

Tobias

**Comment by icdishb** [comment]
Hi Tobias, 
This is a very good suggestion, I added the link to setuptools in the readme file.
