### ISSUE TITLE
multiprocessing in train_test.py 

### ISSUE THREAD

**Issue by tobigithub** [icdishb/fingerid#2]
Hi,
this is for fingerid 1.4, just a question, it seems that there is no multi-processing or parallel training happening from the CPU use. I guess for 1000s of molecules it could matter (sofar its decently fast).

![image](https://cloud.githubusercontent.com/assets/2569565/15559797/2e41bed2-229a-11e6-95e8-92ca982471b3.png)

This is on a 3.1 Ghz CPU workstation, picture above shows only 1 CPU (thread) used from 16.
That was for the standard train_test.py script. 

````R
~/fingerid/examples$ time python train_test.py 

real	0m55.436s
user	0m55.352s
sys	0m1.384s

````

If I change the number of CPUs to 8 it will still be the same time,
trainModels(train_ckm, labels, "MODELS", select_c=False, **n_p=8**, prob=prob)

```R
real	0m55.337s
user	0m55.452s
sys	0m1.528s
`````

Cheers
Tobias

**Comment by icdishb** [comment]
I guess the task in this setting is so small that before another process is started, the previous one is already finished so the new task is running on the same cpu again.

**Comment by icdishb** [comment]
I removed the join function, this prevents using mutli-processes... Now I can see it uses multiple cores.

**Comment by tobigithub** [comment]
Hi,
actually the change you introduced will now create an error, just by executing the script with no modifications.

````R
~/fingerid/examples$ time python train_test.py 
parse data

computing PPK kernels
computing NB kernels
computing NI kernels
computing LB kernels
computing LC kernels
computing LI kernels
computing RLB kernels
computing RLI kernels
computing CPC kernels
computing CP2 kernels
computing CPK kernels
computing CSC kernels

combine kernels

Computing combined kernel for ALIGN
train models and make prediction
Create directory MODELS to store the trained models
pred on 0'th label
can't open model file MODELS/0.model
Traceback (most recent call last):
  File "train_test.py", line 102, in <module>
    preds = predModels(test_ckm, n_fp, "MODELS", prob=prob)
  File "../../fingerid/fingerid/model/predSVM.py", line 42, in predModels
    p_label, p_acc, p_val = svm_predict(dummy_y, test_km, m, '-b 1 -q')
  File "/home/ubuntu/libsvm-3.21/python/svmutil.py", line 212, in svm_predict
    svm_type = m.get_svm_type()
AttributeError: 'NoneType' object has no attribute 'get_svm_type'

real	0m55.565s
user	0m56.532s
sys	0m1.184s
````

Tobias
