### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_svm_type'

### ISSUE THREAD

**Issue by tobigithub** [icdishb/fingerid#6]
See error introduced after first change.
AttributeError: 'NoneType' object has no attribute 'get_svm_type'
[Issue #2 ](https://github.com/icdishb/fingerid/issues/2)

(I had to open new issue, because could not re-open the old issue #2 ).
Tobias

**Comment by icdishb** [comment]
Hi, I should block the program before the started processes all finished. Now it should be ok, please checkout the latest version.
